# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoundOfRain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoundOfRain

  inhibit_all_warnings!

  pod 'SnapKit'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'

  target 'SoundOfRainTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoundOfRainUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
